import turtle
t=turtle.Turtle()
t.penup()
t.goto(-250,195)
t.color("black")
t.pendown()
t.begin_fill()
t.color("dark green")
for i in range(2):
    t.fd(500)
    t.right(90)
    t.fd(300)
    t.right(90)
t.end_fill()
t.penup()
t.goto(-30,-30)
t.pendown()
t.pendown()
t.begin_fill()
t.color("red")
t.circle(75)
t.end_fill()
t.hideturtle()

